//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Star
    {
        public int id { get; set; }
        public string nameOfStar { get; set; }
        public double x { get; set; }
        public double y { get; set; }
        public int idOfConstellation { get; set; }
        public int chain { get; set; }
    
        public virtual Constellation Constellation { get; set; }
        
        public override string ToString()
        {
            return nameOfStar;
        }
    }
}
