//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stars
    {
        public int id { get; set; }
        public string nameOfStar { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
        public int galaxyID { get; set; }
        public Nullable<bool> flag { get; set; }
    
        public virtual Galaxies Galaxies { get; set; }
    }
}
